development:
  adapter: postgresql
  encoding: unicode
  database: mebey
  pool: 5
  username: bmrocha
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: mebey_test
  pool: 5
  username: bmrocha
  password: 123456
